import fs from 'node:fs';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {gunzipSync} from 'node:zlib';
import {build} from 'esbuild';
import {Box3,Vector3} from 'three';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
const root='public/models/v13.6/Fired_Heater_Atlas_Web_V13_6';
const bytes=fs.readFileSync(root+'.glb');
const expected=fs.readFileSync('docs/upgrade/master.sha256','utf8').trim().split(' ')[0];
assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),expected,'Untouched master checksum');
assert(bytes.equals(gunzipSync(fs.readFileSync('source-assets/v13.6/Fired_Heater_Atlas_Web_V13_6.glb.gz'))),'Archive must preserve every original GLB byte');
const manifest=JSON.parse(fs.readFileSync(root+'_manifest.json'));
const profile=JSON.parse(fs.readFileSync(root+'_scene_profile.json'));
const gltf=await new Promise((resolve,reject)=>new GLTFLoader().parse(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'',resolve,reject));
gltf.scene.updateMatrixWorld(true);
const meshes=[];gltf.scene.traverse(o=>{if(o.isMesh)meshes.push(o)});
assert.equal(meshes.length,1067);assert.equal(gltf.cameras.length,24);
assert.equal(new Set(meshes.map(o=>o.userData.atlas_source_name||o.name)).size,1067);
const names=new Set(manifest.objects.flatMap(o=>[o.name,o.source_name]));
for(const mesh of meshes)assert(names.has(mesh.userData.atlas_source_name||mesh.name),`Missing semantics ${mesh.name}`);
for(const camera of gltf.cameras){const p=profile.cameras.find(c=>c.name===camera.name);assert(p);assert(camera.position.distanceTo(new Vector3(p.position[0],p.position[2],-p.position[1]))<.0001,`Camera transform ${camera.name}`);}
const flames=meshes.filter(m=>profile.material_profiles[m.material.name]?.profile_type==='flame_procedural');assert.equal(flames.length,12);
for(const flame of flames){const b=new Box3().setFromObject(flame);assert(b.min.y>=5.3&&b.max.y<14.5,'Normal firebox envelope');assert(b.min.x>-4.1&&b.max.x<4.1,'Normal radiant clearance');}
const moduleFrom=async file=>{const r=await build({entryPoints:[file],bundle:true,write:false,platform:'node',format:'esm'});return import('data:text/javascript;base64,'+Buffer.from(r.outputFiles[0].text).toString('base64'))};
const {semanticName,catalog}=await moduleFrom('src/v136/semantics.ts');
const inventory=Object.fromEntries(catalog.map(c=>[c.name,manifest.objects.filter(o=>semanticName(o,o.name)===c.name).length]));
assert.equal(inventory['Tube Supports'],0,'Source limitation must remain explicit');
for(const [part,count] of Object.entries(inventory))if(part!=='Tube Supports')assert(count>0,part);
for(const o of manifest.objects.filter(o=>/FlameScanner/.test(o.name)))assert.equal(semanticName(o,o.name),'Flame Scanner');
const {trainingState}=await moduleFrom('src/v136/training.ts');
const base={mode:'cutaway',selected:'',labels:true,flow:true,explode:false,contextMode:'full',damperPosition:18,cameraCommand:{id:0,action:'fitHeater'},onSelect:()=>{}};
const state=(operationState,operationFocus='',extra={})=>trainingState({...base,operationState,operationFocus,...extra});
for(const key of ['safeNonFiring','readiness','processReady','purgeReady','purgeActive','purgeComplete']){assert.equal(state(key).main,0);assert.equal(state(key).pilot,false)}
assert.deepEqual(state('purgeActive').flows,['process','purge']);
assert.equal(state('pilotIgnition').main,0);assert.equal(state('pilotIgnition').pilot,true);
assert.equal(state('pilotProven','pilotNotEstablished').pilot,false);
assert.equal(state('pilotProven','pilotNotProven').pilot,true);
assert(state('normalOperation').main>0);
assert(state('controlledShutdown','shutdownStable').main>state('controlledShutdown','shutdownReduced').main);
assert.equal(state('controlledShutdown','shutdownFiringRemoved').main,0);
assert.equal(state('coolDownNonFiring').main,0);
assert(state('coolDownNonFiring','cooldownResidual').heat>state('coolDownNonFiring','cooldownNonFiring').heat);
assert(state('loadChange','loadIncrease').main>state('loadChange','loadDecrease').main);
assert.equal(state(undefined,'',{fault:'draftPressure',faultLevel:1}).restriction,96);
assert.equal(state(undefined,'',{fault:'draftPressure',compareNormal:true}).fault,null);
assert.equal(state(undefined,'',{fault:'scannerConcern'}).main,1);
assert.equal(state(undefined,'',{fault:'pilotFailure',faultLevel:0}).pilot,true,'Zero fault severity restores pilot');
assert.equal(state(undefined,'',{fault:'refractoryDamage',faultLevel:0}).fault,null,'Zero fault severity restores normal materials');
assert.equal(state('controlledShutdown','shutdownConcern').level,1,'Shutdown concern has a visible severity');
fs.writeFileSync('docs/upgrade/component-inventory.json',JSON.stringify(inventory,null,2)+'\n');
console.log('[qa:v13.6] PASS — checksum, 1067 semantic meshes, 24 source cameras, normal flame envelope, scanner identity, O-00 to O-14 render contracts');
