import type { FaultId } from './types';
export type FaultCase = {id:FaultId;title:string;system:string;part:string;see:string;change:string;causes:string[];check:string;why:string;related:string[]};
export const faults:FaultCase[]=[
 {id:'flameImpingement',title:'Flame impingement',system:'COMBUSTION',part:'Radiant Tubes',see:'One flame bends toward a radiant tube; a local hot-area cue appears at contact.',change:'The flame envelope loses its normal clearance from the tube.',causes:['Distorted fuel distribution or damaged tip','Poor air distribution or an unsuitable firing pattern'],check:'Compare adjacent flames, burner hardware, tube appearance and relevant process-flow indications.',why:'Concentrated heat input can exceed the local cooling available from the process fluid.',related:['Burners','Fuel Tip / Gas Gun','Radiant Tubes']},
 {id:'tubeHotArea',title:'Tube hot area',system:'RADIANT',part:'Radiant Tubes',see:'A small area is hotter-looking than neighboring tube surfaces.',change:'Local heat input and local heat removal are no longer balanced.',causes:['Local flame exposure','Flow imbalance or internal deposits'],check:'Compare tube skin indications, pass flow and nearby flame patterns. Color is a qualitative cue here.',why:'The pattern is a reason to investigate; color alone does not establish a temperature or a cause.',related:['Radiant Tubes','Tube Skin Sensors','Burners']},
 {id:'draftPressure',title:'Positive firebox pressure',system:'DRAFT',part:'Breeching',see:'Evacuation slows and hot gas tends outward at an opening.',change:'Increasing downstream resistance reduces the inward containment margin.',causes:['Restricted stack damper','Plugged convection passages or other draft-path problems'],check:'Compare arch/firebox pressure with actual damper movement and gas-path condition.',why:'Hot gas escaping from openings is a pressure-containment problem. It is distinct from premix flashback.',related:['Stack Damper','Draft Instruments','Convection Bank','Sight Port']},
 {id:'convectionFouling',title:'Convection fouling',system:'HEAT RECOVERY',part:'Convection Bank',see:'Deposit surfaces build around the convection rows.',change:'Deposits obstruct gas passages and reduce effective heat transfer.',causes:['Fuel contaminants and combustion deposits','Ineffective or unavailable cleaning under the applicable design'],check:'Compare draft, gas-path differential pressure if available, duty and stack-temperature trends.',why:'A fouled bank can affect both useful heat recovery and gas-path resistance.',related:['Convection Bank','Shield Tubes','Stack']},
 {id:'highStackTemperature',title:'High stack temperature',system:'HEAT RECOVERY',part:'Stack',see:'Hotter-looking combustion products remain visible into the stack.',change:'In this example, less heat is removed before the products reach the outlet.',causes:['Underperforming heat recovery or fouling','Changed duty, excess air, air ingress or operating configuration'],check:'Compare stack-temperature trend with firing, process duty, oxygen and the heat-recovery section.',why:'Higher stack temperature can indicate unrecovered energy; fouling is only one possible cause.',related:['Convection Bank','Stack Analyzers','Stack']},
 {id:'flameout',title:'Burner flameout',system:'COMBUSTION',part:'Burners',see:'One main flame disappears while neighboring flames remain visible.',change:'Flame absence creates a different condition from the healthy firing pattern.',causes:['Fuel interruption','Air/draft disturbance or burner instability'],check:'Distinguish the visual loss from the real flame-proving signal and approved protective response.',why:'The animation does not determine BMS voting, trip timing or what other burners do in a specific plant.',related:['Burners','Flame Scanner','Fuel Gas Train']},
 {id:'instability',title:'Pulsation / huffing',system:'COMBUSTION',part:'Burners',see:'The flame envelopes oscillate repeatedly.',change:'Unsteady combustion can couple with pressure fluctuations in the furnace.',causes:['Fuel/air delivery disturbances','Burner or furnace acoustic interaction'],check:'Compare sound, flame movement, draft trend and fuel/air stability using approved observation methods.',why:'Instability can disturb combustion and load the enclosure; this is not an explosion simulation.',related:['Burners','Air Register','Draft Instruments']},
 {id:'unevenFiring',title:'Uneven firing',system:'COMBUSTION',part:'Burners',see:'One flame is noticeably shorter than the other three.',change:'Heat release is distributed unevenly across the burner bank.',causes:['Unequal fuel distribution','Register mismatch, deposits or different burner condition'],check:'Compare individual flame envelopes with burner condition and relevant indications.',why:'Uniform-looking flames are only one observation; an uneven pattern can change tube heat exposure.',related:['Burners','Fuel Gas Train','Air Register']},
 {id:'airLeakage',title:'Downstream air leakage',system:'DRAFT',part:'Convection Bank',see:'Pale air enters the upper heater downstream of the burner zone.',change:'Leakage mixes oxygen into products after the main combustion region.',causes:['Casing, door or joint leakage under negative pressure','Other unintended air-entry paths'],check:'Compare stack oxygen with radiant/bridgewall oxygen where available and inspect likely leakage paths.',why:'More oxygen at the stack does not necessarily mean more useful combustion air at the burner.',related:['Casing & Structure','Stack Analyzers','Air Register']},
 {id:'refractoryDamage',title:'Refractory damage',system:'RADIANT',part:'Refractory',see:'A local lining-loss cue aligns with a casing hot-area cue.',change:'Less insulating material separates the hot enclosure from the casing.',causes:['Spalling or local lining loss','Thermal cycling or mechanical damage'],check:'Relate the external temperature pattern to lining condition and approved inspection evidence.',why:'The visual is a recognition aid; it does not predict structural capacity or safe remaining life.',related:['Refractory','Casing & Structure','Burner Tile']},
 {id:'tipFouling',title:'Burner tip fouling',system:'COMBUSTION',part:'Fuel Tip / Gas Gun',see:'One flame becomes tilted relative to the clean neighboring pattern.',change:'A restricted or damaged discharge region distorts local fuel distribution.',causes:['Deposits at the fuel tip','Mechanical tip damage or misalignment'],check:'Compare the flame pattern and burner history; hardware examination depends on the approved safe condition.',why:'Distortion may lead to unstable combustion, poor mixing or local heat exposure.',related:['Fuel Tip / Gas Gun','Burners','Radiant Tubes']},
 {id:'pilotFailure',title:'Pilot not established',system:'IGNITION',part:'Pilot',see:'An ignition cue is present but the pilot flame is absent.',change:'An ignition attempt is not the same as establishing a flame.',causes:['Pilot fuel or ignition-source issue','Pilot hardware or local air/draft condition'],check:'Separate ignition command, pilot flame and flame-proving indication. Follow the real approved failure sequence.',why:'This study never admits a main flame on the basis of the animation.',related:['Pilot','Igniter','Flame Scanner']},
 {id:'scannerConcern',title:'Flame-proving concern',system:'INSTRUMENTATION',part:'Flame Scanner',see:'Flame remains visible while the training signal status reads “not proven”.',change:'The physical flame and the detection/proving chain are separate.',causes:['Scanner sightline, contamination or signal problem','Wiring or configured proving-system concern'],check:'Compare the approved flame-proving indication with permitted visual observations.',why:'A visible flame does not override the configured protection system.',related:['Flame Scanner','Pilot','Burners']},
 {id:'lowProcessFlow',title:'Low process flow',system:'PROCESS',part:'Radiant Tubes',see:'Process markers move more slowly while a local thermal concern develops.',change:'Reduced process-side heat removal changes the tube cooling margin.',causes:['Low total flow','Pass imbalance or restriction'],check:'Compare actual pass-flow indications, heat input and tube skin trends where available.',why:'Particle speed is qualitative; no alarm setpoint or tube-temperature limit is implied.',related:['Radiant Tubes','Tube Skin Sensors','Burners']},
 {id:'coking',title:'Coking awareness',system:'PROCESS',part:'Radiant Tubes',see:'An enlarged brown deposit sleeve accompanies a local tube hot-area cue.',change:'Internal deposits add resistance between the tube wall and the process fluid.',causes:['Process-fluid behavior and thermal history','Poor flow distribution or local heat exposure'],check:'Review process trends, pass-flow balance and suitable inspection evidence; the sleeve is illustrative.',why:'This view explains the mechanism. It does not estimate coke thickness, tube life or a safe run length.',related:['Radiant Tubes','Tube Skin Sensors']},
];
